server {
    bind_address = "0.0.0.0"
    bind_port = "8081"

    trust_domain = "margo.example.com"
    data_dir = "/run/spire/server/data"
    log_level = "INFO"

    ca_key_type = "ec-p256"
    ca_ttl = "168h"
    default_x509_svid_ttl = "1h"
    default_jwt_svid_ttl = "5m"
}

plugins {
    DataStore "sql" {
        plugin_data {
            database_type = "sqlite3"
            connection_string = "/run/spire/server/data/datastore.sqlite3"
        }
    }

    KeyManager "disk" {
        plugin_data {
            keys_path = "/run/spire/server/data/keys.json"
        }
    }

    NodeAttestor "join_token" {
        plugin_data {}
    }

    UpstreamAuthority "disk" {
        plugin_data {
            cert_file_path = "/etc/spire/upstream/spire-upstream.crt"
            key_file_path = "/etc/spire/upstream/spire-upstream.key"
            bundle_file_path = "/etc/spire/upstream/root.crt"
            upstream_bundle = true
        }
    }
}

health_checks {
    listener_enabled = true
    bind_address = "0.0.0.0"
    bind_port = "8080"
    live_path = "/live"
    ready_path = "/ready"
}
