// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const deleteDeployment = `-- name: DeleteDeployment :exec
DELETE FROM application_deployments
WHERE device_id = ? AND id = ?
`

type DeleteDeploymentParams struct {
	DeviceID string
	ID       string
}

func (q *Queries) DeleteDeployment(ctx context.Context, arg DeleteDeploymentParams) error {
	_, err := q.db.ExecContext(ctx, deleteDeployment, arg.DeviceID, arg.ID)
	return err
}

const getBundleBlobByDigest = `-- name: GetBundleBlobByDigest :one
SELECT digest, archive, created_at
FROM bundle_blobs
WHERE digest = ?
`

func (q *Queries) GetBundleBlobByDigest(ctx context.Context, digest string) (BundleBlob, error) {
	row := q.db.QueryRowContext(ctx, getBundleBlobByDigest, digest)
	var i BundleBlob
	err := row.Scan(&i.Digest, &i.Archive, &i.CreatedAt)
	return i, err
}

const getDeploymentBlobByDigest = `-- name: GetDeploymentBlobByDigest :one
SELECT digest, descriptor, created_at
FROM deployment_blobs
WHERE digest = ?
`

func (q *Queries) GetDeploymentBlobByDigest(ctx context.Context, digest string) (DeploymentBlob, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentBlobByDigest, digest)
	var i DeploymentBlob
	err := row.Scan(&i.Digest, &i.Descriptor, &i.CreatedAt)
	return i, err
}

const getDeploymentByIdAndDigest = `-- name: GetDeploymentByIdAndDigest :one
SELECT d.id, b.descriptor, d.descriptor_digest, d.device_id
FROM application_deployments d
JOIN deployment_blobs b ON b.digest = d.descriptor_digest
WHERE d.device_id = ? AND d.id = ? AND d.descriptor_digest = ?
`

type GetDeploymentByIdAndDigestParams struct {
	DeviceID         string
	ID               string
	DescriptorDigest string
}

type GetDeploymentByIdAndDigestRow struct {
	ID               string
	Descriptor       []byte
	DescriptorDigest string
	DeviceID         string
}

func (q *Queries) GetDeploymentByIdAndDigest(ctx context.Context, arg GetDeploymentByIdAndDigestParams) (GetDeploymentByIdAndDigestRow, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentByIdAndDigest, arg.DeviceID, arg.ID, arg.DescriptorDigest)
	var i GetDeploymentByIdAndDigestRow
	err := row.Scan(
		&i.ID,
		&i.Descriptor,
		&i.DescriptorDigest,
		&i.DeviceID,
	)
	return i, err
}

const getDeploymentsByDeviceId = `-- name: GetDeploymentsByDeviceId :many
SELECT d.id, b.descriptor, d.descriptor_digest, d.device_id
FROM application_deployments d
JOIN deployment_blobs b ON b.digest = d.descriptor_digest
WHERE d.device_id = ?
ORDER BY d.id
`

type GetDeploymentsByDeviceIdRow struct {
	ID               string
	Descriptor       []byte
	DescriptorDigest string
	DeviceID         string
}

func (q *Queries) GetDeploymentsByDeviceId(ctx context.Context, deviceID string) ([]GetDeploymentsByDeviceIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getDeploymentsByDeviceId, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeploymentsByDeviceIdRow
	for rows.Next() {
		var i GetDeploymentsByDeviceIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Descriptor,
			&i.DescriptorDigest,
			&i.DeviceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeviceId = `-- name: GetDeviceId :one
SELECT id FROM devices
WHERE id = ?
`

func (q *Queries) GetDeviceId(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getDeviceId, id)
	err := row.Scan(&id)
	return id, err
}

const getManifestByDeviceId = `-- name: GetManifestByDeviceId :one
SELECT device_id, version, bundle_digest FROM application_deployment_manifests
WHERE device_id = ?
`

func (q *Queries) GetManifestByDeviceId(ctx context.Context, deviceID string) (ApplicationDeploymentManifest, error) {
	row := q.db.QueryRowContext(ctx, getManifestByDeviceId, deviceID)
	var i ApplicationDeploymentManifest
	err := row.Scan(&i.DeviceID, &i.Version, &i.BundleDigest)
	return i, err
}

const insertBundleBlob = `-- name: InsertBundleBlob :exec
INSERT INTO bundle_blobs (digest, archive)
VALUES (?, ?)
ON CONFLICT(digest) DO NOTHING
`

type InsertBundleBlobParams struct {
	Digest  string
	Archive []byte
}

func (q *Queries) InsertBundleBlob(ctx context.Context, arg InsertBundleBlobParams) error {
	_, err := q.db.ExecContext(ctx, insertBundleBlob, arg.Digest, arg.Archive)
	return err
}

const insertDeploymentBlob = `-- name: InsertDeploymentBlob :exec
INSERT INTO deployment_blobs (digest, descriptor)
VALUES (?, ?)
ON CONFLICT(digest) DO NOTHING
`

type InsertDeploymentBlobParams struct {
	Digest     string
	Descriptor []byte
}

func (q *Queries) InsertDeploymentBlob(ctx context.Context, arg InsertDeploymentBlobParams) error {
	_, err := q.db.ExecContext(ctx, insertDeploymentBlob, arg.Digest, arg.Descriptor)
	return err
}

const upsertDeployment = `-- name: UpsertDeployment :exec
INSERT INTO application_deployments (
    id, descriptor_digest, device_id
) VALUES (
    ?, ?, ?
)
ON CONFLICT (device_id, id) 
DO UPDATE SET
    descriptor_digest = excluded.descriptor_digest
`

type UpsertDeploymentParams struct {
	ID               string
	DescriptorDigest string
	DeviceID         string
}

func (q *Queries) UpsertDeployment(ctx context.Context, arg UpsertDeploymentParams) error {
	_, err := q.db.ExecContext(ctx, upsertDeployment, arg.ID, arg.DescriptorDigest, arg.DeviceID)
	return err
}

const upsertManifest = `-- name: UpsertManifest :exec
INSERT INTO application_deployment_manifests (
    version, bundle_digest, device_id
) VALUES (
    ?, ?, ?
)
ON CONFLICT (device_id) 
DO UPDATE SET
    version = excluded.version,
    bundle_digest = excluded.bundle_digest,
    device_id = excluded.device_id
`

type UpsertManifestParams struct {
	Version      int64
	BundleDigest sql.NullString
	DeviceID     string
}

func (q *Queries) UpsertManifest(ctx context.Context, arg UpsertManifestParams) error {
	_, err := q.db.ExecContext(ctx, upsertManifest, arg.Version, arg.BundleDigest, arg.DeviceID)
	return err
}
