FROM golang:1.25-bookworm AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /out/spire-workload ./cmd/spire-workload

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=build --chown=nonroot:nonroot /out/spire-workload /usr/local/bin/spire-workload
USER nonroot:nonroot
ENTRYPOINT ["/usr/local/bin/spire-workload"]
