FROM ghcr.io/spiffe/spire-server:1.10.4 AS spire
FROM alpine:3.20
RUN apk add --no-cache bash ca-certificates jq
COPY --from=spire /opt/spire/bin/spire-server /opt/spire/bin/spire-server
ENTRYPOINT []
