// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type ApplicationDeployment struct {
	ID               string
	DescriptorDigest string
	DeviceID         string
}

type ApplicationDeploymentManifest struct {
	DeviceID     string
	Version      int64
	BundleDigest sql.NullString
}

type BundleBlob struct {
	Digest    string
	Archive   []byte
	CreatedAt time.Time
}

type DeploymentBlob struct {
	Digest     string
	Descriptor []byte
	CreatedAt  time.Time
}

type Device struct {
	ID string
}
